spring:
  flyway:
    url: jdbc:h2:mem:springboottestdb
    schemas: APPSCHEMA
    user: sa
    password:
    locations: filesystem:src/main/resources/sql/migrations

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:springboottestdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.default_schema: APPSCHEMA
    hibernate:
      ddl-auto: none